### PR TITLE
fix(#20) RBAC collector removes labels from labels configMap

### LINKED ISSUE #20: RBAC collector removes labels from labels configMap
When RBAC collector updates the labels configMap, existing labels are removed. We create the configMap via ArgoCD and this attaches the following label to the cm:
```yaml
metadata:
  labels:
    argocd.argoproj.io/instance: multena
```
So after every RBAC collector run we are seeing a diff in ArgoCD.

Ideally, any existing labels/annotations should be preserved during an update of the cm.

### PR DESCRIPTION
**Pull request by fhochleitner**
retain labels and annotations on rbac-configmap by patching the resource instead of using update
fixes #20

### CODE REVIEW

File: util/util.go [hunk 1]
```diff
@@ -15,7 +18,19 @@ func WriteConfigmap(clientset *kubernetes.Clientset, permission map[string]map[s
 	if err != nil {
 		return err
 	}
+	data := strings.Replace(string(permissions), "\n", "\\n", -1)
```
Comment (Lucostus) [inline util/util.go:21]: I think it would be more elegant to add the keys 'data' and 'label.yaml' to a map, and then marshal the entire map, instead of using marshaling and string manipulation.

File: util/util.go [hunk 2]
```diff
@@ -15,7 +18,19 @@ func WriteConfigmap(clientset *kubernetes.Clientset, permission map[string]map[s
...
+	patch := []byte(fmt.Sprintf(`{"data":{"labels.yaml": "%s"}}`, data))
 
+	_, err = clientset.CoreV1().ConfigMaps(c.CMNamespace).Patch(context.Background(), c.CMName, types.MergePatchType, patch, metav1.PatchOptions{})
```
Comment (Lucostus) [inline util/util.go:24]: Does the patch clear all fields that are not included in the 'to be patched' map? Otherwise, users could only gain permissions but not lose them.

**Review by Lucostus — CHANGES_REQUESTED** [review]

File: util/util.go (hunk 2 above)
Comment (fhochleitner) [reply util/util.go:24]: it does. obviously i tested the implementation ;-)

File: util/util.go (hunk 1 above)
Comment (fhochleitner) [reply util/util.go:21]: i never said its pretty
